### PR TITLE
Task/create user profile page

### LINKED ISSUE #13: Create User Profile page
- [x] Display user name.
- [x] Display their profile picture/placeholder picture.
- [x] Display their 
- [ ] Their social media links.
- [x] List of all events they registered for.

### PR DESCRIPTION
**Pull request by AVidhanR**
- created a profile section
- events attended section
- YES, IT IS RESPONSIVE @CharanMN7 
- used the events data from the .json file

### CODE REVIEW

**Comment by CharanMN7** [comment]
Thanks for the contribution!  
One thing tho. Next time, please do not create a pull request if you wrote the code for an issue that you were not assigned for.

**Comment by CharanMN7** [comment]
Change of plans...

**Comment by AVidhanR** [comment]
Okay @CharanMN7

**Comment by AVidhanR** [comment]
Checking the new reply feature in Gmail

**Pull request closed without merging**
