### PR TITLE
Task/create navbar

### PR DESCRIPTION
**Pull request by AVidhanR**
created a navbar folder - check it out in the "task/create-navbar" branch

### CODE REVIEW

**Comment by CharanMN7** [comment]
Please take this into notes:  
To customize the font-style, use it's weights as follows:
headings - 700
normal text - 400
text in buttons, form headings, placeholders - 500

**Review by CharanMN7 — CHANGES_REQUESTED** [review]
Please explain why you had to use the useEffect in NavBar.(suggestion: use sass to achieve the result you’re looking for instead of useEffect)
The buttons in the navbar have a weird effect that appears when pressed. It looks very inconsistent. Please fix that asap. (suggestion: if you need gaps between elements, use margins instead of padding)
Also, you may redeclare mixins in different .scss files but you don’t have to redeclare classes. If you feel like any class is reusable, move it to the index.scss file and write a comment about what it is I a separate commit or I the pul request that includes it.

**Comment by AVidhanR** [comment]
> Please explain why you had to use the useEffect in NavBar.(suggestion: use sass to achieve the result you’re looking for instead of useEffect) The buttons in the navbar have a weird effect that appears when pressed. It looks very inconsistent. Please fix that asap. (suggestion: if you need gaps between elements, use margins instead of padding) Also, you may redeclare mixins in different .scss files but you don’t have to redeclare classes. If you feel like any class is reusable, move it to the index.scss file and write a comment about what it is I a separate commit or I the pul request that includes it.

then how can i do it without using useeffect() @CharanMN7

**Comment by CharanMN7** [comment]
> then how can i do it without using useeffect() @CharanMN7 

So, when a breakpoint occurs, where you don't want to see the about and the icon, just turn their display to none and then you can display: block your hidden hamburger menu and toggle on/off your hidden menu with that button. Refer

**Comment by AVidhanR** [comment]
> > then how can i do it without using useeffect() @CharanMN7
> 
> So, when a breakpoint occurs, where you don't want to see the about and the icon, just turn their display to none and then you can display: block your hidden hamburger menu and toggle on/off your hidden menu with that button. Refer: https://github.com/CharanMN7/Project-Pandora

i get it now @CharanMN7 and 🤣 it's a 2 line code in sass and i turned it to 10 lines in jsx

**Comment by CharanMN7** [comment]
> > > then how can i do it without using useeffect() @CharanMN7
> > 
> > So, when a breakpoint occurs, where you don't want to see the about and the icon, just turn their display to none and then you can display: block your hidden hamburger menu and toggle on/off your hidden menu with that button. Refer: https://github.com/CharanMN7/Project-Pandora
> 
> i get it now @CharanMN7 and 🤣 it's a 2 line code in sass and i turned it to 10 lines in jsx

Haha, cool. We all did sth like that at one point 🙌🏻

**Review by CharanMN7 — APPROVED** [review]

**Comment by CharanMN7** [comment]
Added the NavBar. Igoring responsiveness for now.

**Pull request merged**
